### ISSUE TITLE
`install-master.sh` without tty

### ISSUE THREAD

**Issue by cirocosta** [wedeploy/cli#49]
Hey,

just tried to use  the `curl https://raw.githubusercontent.com/wedeploy/cli/master/install-master.sh -s | bash` directly on a dockerfile and couldn't make it work flawlessly. That's because during  the build there's no tty assigned to the container that does it:

```
+ curl https://raw.githubusercontent.com/wedeploy/cli/master/install-master.sh -s
+ bash
bash: line 31: /dev/tty: No such device or address
```

Note that it won't kill the build as it's not using `Exit Immediately` (`set -e`), but would otherwise. It can probably be solved with that test you mentioned to me: `if [[ -t (...) ]]`.

Thx!

**Comment by henvic** [comment]
It is actually using `set -e` (see `set -euo pipefail`). I just ignore the exit code with a || true:
`read -t 3 -p "" < /dev/tty || true`

https://github.com/wedeploy/cli/blob/94046b910931fd75a02dd4870f112201a5cb042c/install-master.sh#L31

**Comment by cirocosta** [comment]
cool, thx @henvic !
