### ISSUE TITLE
Creating project - in the root or a subdir

### ISSUE THREAD

**Issue by igorspasic** [wedeploy/cli#71]
Hey @eduardolundgren with `we create <foo>`, we will create `project.json` in current folder. I was expecting more to be a folder with the ID. 

It's like you say `git clone foo`, it will create a sub folder `foo`

wdyt?

**Comment by eduardolundgren** [comment]
You meant, `we create foo` to create a folder with a project.json with id "foo" or a folder "foo"? Could you detail a bit more? thx.

**Comment by igorspasic** [comment]
Yes, so:

    > we create

It asks for the `ID`, `name`, etc. This may create folder: `foo` with `project.json` inside. In the same way:

    > we create foo

would create folder `foo` with `project.json`?

Similar for subfolders?

Just an idea - I was expecting folder to be created, like when git is cloning, that is all.

**Comment by eduardolundgren** [comment]
Yeah, so this will create the folder and set the project.json id to "foo".

/cc @henvic wdyt?

**Comment by igorspasic** [comment]
And similar for containers i.e. subfolders.

Just telling what I expected from using the CLI; haven't use for some time, so its like all new to me 😄

**Comment by eduardolundgren** [comment]
No problem, keep sharing if you have other suggestions.

**Comment by henvic** [comment]
I like this.

On git we have `git clone <repo> <directory>`.

If directory is given, it will clone the repo there. We can follow the same pattern.

**Comment by henvic** [comment]
And, of course, if you are at <dir>/<subdir> and <dir> has a project.json (by design we just traverse the first-level) and subdir has no container.json, when you do `we create` it will try to create a container there.
