### ISSUE TITLE
Rename `--follow` to `--watch` in `we logs`

### ISSUE THREAD

**Issue by cirocosta** [wedeploy/cli#72]
Hey,

as in `we list` there's the `--watch` flag, when using `we logs` i immediately tried that same flag (as i expected a similar result: attach to the logs of the container). Wdyt about keeping a standard and using just `--watch` instead of `--follow`? 

```
 dashboard git:(build-placeholder) ✗ we list --help
List projects and containers running on WeDeploy

Usage:
  we list or list [project] to filter by project [flags]

Flags:
  -d, --detailed   Show more containers details.
      --watch      Watch for changes.


-----------------------
 dashboard git:(build-placeholder) ✗ we logs --help                   
Logs running on WeDeploy

Usage:
  we logs [project] [container] [instance] [flags]

Examples:
we logs (on container directory)
we logs portal email
we logs portal email email5932

Flags:
  -f, --follow         Follow log output
      --level string   Severity (critical, error, warning, info (default), debug)
      --since string   Show since moment (i.e., 20min, 3h, UNIX timestamp)


```

Thx!

**Comment by henvic** [comment]
Actually I did this 34h ago.

Closed by 920302ddfd620d4d283c83a357d641baa8cf29f4.

**Comment by henvic** [comment]
Just now I realized I haven't done any pushes or releases for 34h+. Sorry about that.

**Comment by henvic** [comment]
Just for claryfication: the reason why I was using --follow / -f before was that docker logs uses this naming.
