### ISSUE TITLE
Copy url to clipboard after "we link"

### ISSUE THREAD

**Issue by eduardolundgren** [wedeploy/cli#77]
Would be cool to copy the url to clipboard after a we link in a container or project.

1) If run from a project copy project url.
2) If run from a container copy container url.

In any case this should say in the logs: 

```
Project Name name.wedeploy.me
● Api api.dashboard.wedeploy.me wedeploy/maven up (Url copied to clipboard)
```

We can also have a `--no-clipboard` option.

**Comment by henvic** [comment]
What about opening the url after linking (see also #74) instead of copying the URL and having a --no-browser flag instead?

It has less unexpected side-effects (i.e., it doesn't destroy data existing currently on the user's clipboard) and is more obvious / visual.

**Comment by cirocosta** [comment]
i'm with @henvic on this, i'd really not like to have something put into my clipboard automatically, but at the same time i'm against  openning the browser as well. 

It looks for me that `we link` should just do the linking (deploy w/ `source`) and that's it; more stuff could be activated through flags, not the other way around. Wdyt?

**Comment by eduardolundgren** [comment]
SGTM. Thanks!
