### ISSUE TITLE
Incrementally linking new containers leads to bad error messages

### ISSUE THREAD

**Issue by cirocosta** [wedeploy/cli#90]
Hey,

during development it's pretty tempting to create a container, then `we link` at project level, then create another container and then `we link` at project level again. The expectation is that the newly added container is linked and the one that has already been linked will just stay there up and running. That's what currently happens but there's a "not very welcoming" error message that comes from doing so:

```
 wechat  we link
Project WeChat wechat.wedeploy.me                                UNKNOWN 
● Static Assets       static.wechat.wedeploy.me         wedeploy/hosting    up
/tmp/techtalk/wechat/static/ dir error: WeDeploy API error: 400 Bad Request (PUT http://localhost:8080/depProject WeChat wechat.wedeploy.me                                  WARN   
● data                data.wechat.wedeploy.me           wedeploy/data       up
● Static Assets       static.wechat.wedeploy.me         wedeploy/hosting    up
Error: List of errors (format is container path: error)
/tmp/techtalk/wechat/static: WeDeploy API error: 400 Bad Request (PUT http://localhost:8080/deploy?containerId=static&projectId=wechat&source=%2Ftmp%2Ftechtalk%2Fwechat%2Fstatic)
	containerAlreadyExists: containerAlreadyExists
```

Do you think we could improve this? I known it's great to have such error as if i create another `container.json` that uses the same `id` i'd be doing something really wrong, but in this case.. it really scares unnecessarily i think.

Wdyt?

**Comment by henvic** [comment]
You should either send me a 304 Not Modified or 200 OK (and might send me a 201 Created when it is created, instead).

However, if you send me a 400 Bad Request I can't do much but to show the error message. Doing anything else (as easy as it would be from the CLI side of things) would open room for error, a lot of special handling with no real benefit, and we can't take the risks associated with missing valuable error handling disappearing as a possible side-effect.

**Comment by henvic** [comment]
Closed with https://github.com/wedeploy/dashboard/commit/16ed3e6ac0198193f9ac0c544d526dfc60488e6b
